/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated.search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated.admin.logs'
import { Route as AuthenticatedResultsSearchIdRouteImport } from './routes/_authenticated.results.$searchId'
import { Route as ApiPublicResultsRouteImport } from './routes/api.public.results'
import { Route as ApiPublicStartSearchRouteImport } from './routes/api.public.start-search'
import { Route as ApiPublicHooksScheduledTaskRouteImport } from './routes/api.public.hooks.scheduled-task'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultsSearchIdRoute =
  AuthenticatedResultsSearchIdRouteImport.update({
    id: '/results/$searchId',
    path: '/results/$searchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicResultsRoute = ApiPublicResultsRouteImport.update({
  id: '/api/public/results',
  path: '/api/public/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStartSearchRoute = ApiPublicStartSearchRouteImport.update({
  id: '/api/public/start-search',
  path: '/api/public/start-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScheduledTaskRoute =
  ApiPublicHooksScheduledTaskRouteImport.update({
    id: '/api/public/hooks/scheduled-task',
    path: '/api/public/hooks/scheduled-task',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/results/$searchId': typeof AuthenticatedResultsSearchIdRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/start-search': typeof ApiPublicStartSearchRoute
  '/api/public/hooks/scheduled-task': typeof ApiPublicHooksScheduledTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/results/$searchId': typeof AuthenticatedResultsSearchIdRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/start-search': typeof ApiPublicStartSearchRoute
  '/api/public/hooks/scheduled-task': typeof ApiPublicHooksScheduledTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/results/$searchId': typeof AuthenticatedResultsSearchIdRoute
  '/api/public/results': typeof ApiPublicResultsRoute
  '/api/public/start-search': typeof ApiPublicStartSearchRoute
  '/api/public/hooks/scheduled-task': typeof ApiPublicHooksScheduledTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/admin/logs'
    | '/results/$searchId'
    | '/api/public/results'
    | '/api/public/start-search'
    | '/api/public/hooks/scheduled-task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/admin/logs'
    | '/results/$searchId'
    | '/api/public/results'
    | '/api/public/start-search'
    | '/api/public/hooks/scheduled-task'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/_authenticated/admin/logs'
    | '/_authenticated/results/$searchId'
    | '/api/public/results'
    | '/api/public/start-search'
    | '/api/public/hooks/scheduled-task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicResultsRoute: typeof ApiPublicResultsRoute
  ApiPublicStartSearchRoute: typeof ApiPublicStartSearchRoute
  ApiPublicHooksScheduledTaskRoute: typeof ApiPublicHooksScheduledTaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/$searchId': {
      id: '/_authenticated/results/$searchId'
      path: '/results/$searchId'
      fullPath: '/results/$searchId'
      preLoaderRoute: typeof AuthenticatedResultsSearchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/results': {
      id: '/api/public/results'
      path: '/api/public/results'
      fullPath: '/api/public/results'
      preLoaderRoute: typeof ApiPublicResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/start-search': {
      id: '/api/public/start-search'
      path: '/api/public/start-search'
      fullPath: '/api/public/start-search'
      preLoaderRoute: typeof ApiPublicStartSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scheduled-task': {
      id: '/api/public/hooks/scheduled-task'
      path: '/api/public/hooks/scheduled-task'
      fullPath: '/api/public/hooks/scheduled-task'
      preLoaderRoute: typeof ApiPublicHooksScheduledTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedResultsSearchIdRoute: typeof AuthenticatedResultsSearchIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedResultsSearchIdRoute: AuthenticatedResultsSearchIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicResultsRoute: ApiPublicResultsRoute,
  ApiPublicStartSearchRoute: ApiPublicStartSearchRoute,
  ApiPublicHooksScheduledTaskRoute: ApiPublicHooksScheduledTaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
